### ISSUE TITLE
A few questions about rustkpi-kmod

### ISSUE THREAD

**Issue by andoriyu** [johalun/rustkpi#1]
Hello,

I read your thesis and read whole code, but still can't figure out what the point of rustpki module if all of its content is present in other `rustpki-hello` and `rustpki-e1000`? On the diagram it looks like sub-modules using stuff from it, but I don't see where in code it's happening...

**Comment by johalun** [comment]
Hey!
Are you referring to libkernel.rlib being linked to e1000 and helloworld? I have to refresh my memory a bit. IIRC, it's only used at compile time and the actual content of libkernel.rlib is not included in the resulting static library.

**Comment by koobs** [comment]
Ping @andoriyu :)

**Comment by andoriyu** [comment]
> Ping @andoriyu :)

@koobs sup? I had very little progress in this space unfortunately.

**Comment by koobs** [comment]
> Are you referring to libkernel.rlib being linked to e1000 and helloworld? 

@andoriyu @johalun asked ^^ and I pinged in case you missed it and can recall the specifics of your question from 3 years ago :)

**Comment by andoriyu** [comment]
> > Are you referring to libkernel.rlib being linked to e1000 and helloworld? 
> 
> @andoriyu @johalun asked ^^ and I pinged in case you missed it and can recall the specifics of your question from 3 years ago :)
> 

Oh, i think i caught @johalun in irc and we talked about it. 

But the question was about some additional `.ko` loaded that didn't do anything.
